name: Print JVM thread dumps
description: Prints a thread dump for all running JVMs
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        for java_pid in $(jps -q -J-XX:+PerfDisableSharedMem); do
          echo "------------------------ pid $java_pid ------------------------"
          jcmd $java_pid Thread.print -l
        done
        exit 0