github-organization-name: "spring-projects"
github-repository-name: "spring-boot"
github-repository-uri: "https://github.com/spring-projects/spring-boot.git"
homebrew-tap-repo: "https://github.com/spring-io/homebrew-tap.git"
docker-hub-organization: "springci"
docker-hub-repository-prefix: "spring-boot"
artifactory-url: "https://repo.spring.io"
branch: "3.0.x"
milestone: "3.0.x"
build-name: "spring-boot"
concourse-url: "https://ci.spring.io"
task-timeout: 2h00m
